const SITE = "https://www.peekr.app";

// We have 4 sitemaps generated by app/sitemap.ts via generateSitemaps()
// (ids 0..3). Next.js exposes each at /sitemap/{id}.xml. This route
// returns the sitemap index that points to all of them so Google can
// discover every URL through a single submitted sitemap.
const SITEMAP_IDS = [0, 1, 2, 3];

export function GET() {
  const now = new Date().toISOString();

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${SITEMAP_IDS.map(
    (id) => `  <sitemap>
    <loc>${SITE}/sitemap/${id}.xml</loc>
    <lastmod>${now}</lastmod>
  </sitemap>`,
  ).join("\n")}
</sitemapindex>`;

  return new Response(xml, {
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
      "Cache-Control": "public, max-age=3600, s-maxage=3600",
    },
  });
}
