import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  async redirects() {
    return [
      // Non-www → www (canonical domain)
      {
        source: "/:path*",
        has: [{ type: "host", value: "peekr.app" }],
        destination: "https://www.peekr.app/:path*",
        permanent: true,
      },
      // Buzz articles published without language prefix → /es/buzz/:slug
      {
        source: "/buzz/:slug",
        destination: "/es/buzz/:slug",
        permanent: true,
      },
      {
        source: "/index.html",
        destination: "/",
        permanent: true,
      },
      // Legacy /xx/login and /xx/signup → root (these pages live outside [lang])
      {
        source: "/:lang(es|en|pt)/login",
        destination: "/login",
        permanent: true,
      },
      {
        source: "/:lang(es|en|pt)/signup",
        destination: "/signup",
        permanent: true,
      },
      // Legacy /xx/user/username → /xx/u/username
      {
        source: "/:lang(es|en|pt)/user/:username",
        destination: "/:lang/u/:username",
        permanent: true,
      },
      // Flutter genera /person/:id → /es/actor/:id
      {
        source: "/person/:id",
        destination: "/es/actor/:id",
        permanent: false,
      },
    ];
  },

  async rewrites() {
    return {
      beforeFiles: [],
      afterFiles: [],
      // fallback: checked LAST — only when no filesystem page or dynamic route
      // matched. This is the correct tier for the vanity username rewrite:
      // /es/buzz → [lang]/buzz/page.tsx matches first (never reaches fallback)
      // /es/jmartinelli → no matching page → falls through to this rewrite
      fallback: [
        // Vanity username with lang prefix but missing /u/ segment.
        // Handles: /pt/jmartinelli → /pt/u/jmartinelli
        // Generated by the lang switcher when current URL is /jmartinelli
        // (middleware rewrite keeps the short URL in the browser bar).
        {
          source: "/:lang(es|en|pt)/:username([a-zA-Z0-9._-]+)",
          destination: "/:lang/u/:username",
        },
      ],
    };
  },

  async headers() {
    return [
      {
        source: "/apple-app-site-association",
        headers: [
          { key: "Content-Type", value: "application/json" },
          {
            key: "Cache-Control",
            value: "public, max-age=300, must-revalidate",
          },
        ],
      },
      {
        source: "/.well-known/apple-app-site-association",
        headers: [
          { key: "Content-Type", value: "application/json" },
          {
            key: "Cache-Control",
            value: "public, max-age=300, must-revalidate",
          },
        ],
      },
      {
        source: "/.well-known/assetlinks.json",
        headers: [
          { key: "Content-Type", value: "application/json" },
          {
            key: "Cache-Control",
            value: "public, max-age=300, must-revalidate",
          },
        ],
      },
    ];
  },

  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "image.tmdb.org",
      },
    ],
  },
};

export default nextConfig;
