import { Lang } from "./_shared";

// All UI strings for the creator dashboard, in es / en / pt.
// Interpolated strings are functions.

export type DashTexts = ReturnType<typeof dashTexts>;

const DICT = {
  es: {
    // page
    metricsFor: "Métricas de",
    tabCountry: "Métricas del País",
    tabTitles: "Métricas de Títulos",
    presetToday: "Hoy",
    presetYesterday: "Ayer",
    preset7d: "7 días",
    preset30d: "30 días",
    preset90d: "90 días",
    custom: "Personalizado",
    onlyOnboarded: "Solo onboarded",
    onlyOnboardedTip: "Considerar solo usuarios que completaron onboarding",
    loading: "Cargando…",
    denied: "Acceso no autorizado",
    // country tab
    loadingMetrics: "Cargando métricas…",
    globalTitle: "Global del país",
    globalSub: "Totales acumulados (toda la historia)",
    totalUsers: "Usuarios totales",
    onboardingDone: "Onboarding completo",
    totalRatings: "Ratings totales",
    inWatchlist: "En watchlist",
    audienceTitle: "Audiencia del período",
    audienceSub: "Installs y onboarding en el rango seleccionado",
    newInstalls: "Nuevos installs",
    prevPeriod: (n: string) => `Período previo: ${n}`,
    onboardingRate: "Tasa de onboarding",
    growthTitle: "Crecimiento de audiencia",
    growthSub: "Usuarios acumulados del país en el período",
    platformTitle: "Plataforma",
    platformSub: "Nuevos installs por plataforma",
    providerTitle: "Provider",
    providerSub: "Método de registro (Google / Apple / email)",
    retentionTitle: "Retención",
    retentionSub: (days: string, plural: boolean) =>
      `Promedio diario del período (${days} día${plural ? "s" : ""}). Uso real = navegó contenido o hizo una acción. 'contrib' = solo acciones explícitas post-install.`,
    dauAvg: "DAU prom/día",
    wauAvg: "WAU prom/día",
    mauAvg: "MAU prom/día",
    northStarAvg: "North Star prom/día",
    weuHint: "WEU (cuentas ≥7d)",
    dauMau: "DAU / MAU",
    stickyDaily: "Stickiness diario",
    wauMau: "WAU / MAU",
    stickyWeekly: "Stickiness semanal",
    churnRisk: "En riesgo de churn",
    resurrected: "Resucitados",
    firstTimeActive: "Activos por 1ª vez",
    thisWeek: "Esta semana",
    contrib: (n: number) => `contrib: ${n}`,
    wowTitle: "Retención semana a semana (WoW)",
    wowSub: "% de activos de una semana que vuelven la siguiente",
    dailyDauTitle: "Actividad diaria (DAU)",
    dailyDauSub: "Usuarios activos por día en el período",
    behaviorTitle: "Comportamiento",
    behaviorSub: (n: string) => `Usuarios activos en el período: ${n}`,
    ratings: "Ratings",
    perActive: (n: number) => `${n} por activo`,
    comments: "Comentarios",
    watchlist: "Watchlist",
    peeklistsCreated: "Peeklists creadas",
    items: (n: string) => `${n} ítems`,
    likesTitles: "Likes (títulos)",
    likesComments: "Likes (comentarios)",
    follows: "Follows",
    mutual: (n: string) => `${n} mutuos`,
    ratersReturning: "Rateadores retornando",
    ratersHint: "Cuentas ≥7d que ratearon (7d)",
    appTitle: "Uso de la app",
    appSub: "Tiempo en app y secciones más navegadas (screen_views desde 29-may, duración capada a 10 min/pantalla)",
    timePerUser: "Tiempo / usuario",
    median: (n: number) => `Mediana: ${n} min`,
    totalTime: "Tiempo total",
    perScreen: "Por pantalla",
    usersWithNav: "Usuarios con navegación",
    mostNavigated: "Secciones más navegadas",
    noData: "Sin datos",
    minShort: "min",
    // titles tab
    loadingTitles: "Cargando títulos…",
    noDataPeriod: "Sin datos en el período",
    noDataTmdb: "Sin datos de TMDB",
    moviesMostViewed: "Películas más vistas en Peekr",
    seriesMostViewed: "Series más vistas en Peekr",
    mostViewedSub: "Por cantidad de vistas en el país y período",
    moviesTopPeekr: "Películas mejor rateadas en Peekr",
    seriesTopPeekr: "Series mejor rateadas en Peekr",
    topPeekrSub: "Promedio de rating de usuarios del país (mín. 3 ratings)",
    moviesTopTmdb: "Películas mejor rateadas en TMDB",
    seriesTopTmdb: "Series mejor rateadas en TMDB",
    topTmdbSub: "vote_average de TMDB entre los títulos activos del período",
    actorsTitle: "Actores trending (TMDB)",
    actorsSub: "Personas en tendencia esta semana — global (TMDB no permite filtrar por región)",
    badgeViews: (n: string) => `${n} vistas`,
    // section labels
    sec_feed: "Feed",
    sec_explore: "Explorar",
    sec_explore_search: "Buscador (Explore)",
    sec_activity: "Actividad",
    sec_activity_ranking: "Ranking",
    sec_inbox: "Inbox",
    sec_profile: "Perfil propio",
    sec_title: "Ficha de título",
    sec_detail: "Detalle de título",
    sec_actor: "Actor",
    sec_user: "Perfil de usuario",
    sec_peeklist: "Peeklist",
    sec_watchlist: "Watchlist",
  },
  en: {
    metricsFor: "Metrics for",
    tabCountry: "Country Metrics",
    tabTitles: "Title Metrics",
    presetToday: "Today",
    presetYesterday: "Yesterday",
    preset7d: "7 days",
    preset30d: "30 days",
    preset90d: "90 days",
    custom: "Custom",
    onlyOnboarded: "Onboarded only",
    onlyOnboardedTip: "Only count users who completed onboarding",
    loading: "Loading…",
    denied: "Access denied",
    loadingMetrics: "Loading metrics…",
    globalTitle: "Country totals",
    globalSub: "All-time cumulative totals",
    totalUsers: "Total users",
    onboardingDone: "Onboarding completed",
    totalRatings: "Total ratings",
    inWatchlist: "In watchlist",
    audienceTitle: "Audience (period)",
    audienceSub: "Installs and onboarding in the selected range",
    newInstalls: "New installs",
    prevPeriod: (n: string) => `Previous period: ${n}`,
    onboardingRate: "Onboarding rate",
    growthTitle: "Audience growth",
    growthSub: "Cumulative country users over the period",
    platformTitle: "Platform",
    platformSub: "New installs by platform",
    providerTitle: "Provider",
    providerSub: "Sign-up method (Google / Apple / email)",
    retentionTitle: "Retention",
    retentionSub: (days: string, plural: boolean) =>
      `Daily average over the period (${days} day${plural ? "s" : ""}). Real usage = browsed content or took an action. 'contrib' = explicit post-install actions only.`,
    dauAvg: "DAU avg/day",
    wauAvg: "WAU avg/day",
    mauAvg: "MAU avg/day",
    northStarAvg: "North Star avg/day",
    weuHint: "WEU (accounts ≥7d)",
    dauMau: "DAU / MAU",
    stickyDaily: "Daily stickiness",
    wauMau: "WAU / MAU",
    stickyWeekly: "Weekly stickiness",
    churnRisk: "Churn risk",
    resurrected: "Resurrected",
    firstTimeActive: "First-time active",
    thisWeek: "This week",
    contrib: (n: number) => `contrib: ${n}`,
    wowTitle: "Week-over-week retention (WoW)",
    wowSub: "% of a week's actives that return the next week",
    dailyDauTitle: "Daily activity (DAU)",
    dailyDauSub: "Active users per day over the period",
    behaviorTitle: "Behavior",
    behaviorSub: (n: string) => `Active users in the period: ${n}`,
    ratings: "Ratings",
    perActive: (n: number) => `${n} per active`,
    comments: "Comments",
    watchlist: "Watchlist",
    peeklistsCreated: "Peeklists created",
    items: (n: string) => `${n} items`,
    likesTitles: "Likes (titles)",
    likesComments: "Likes (comments)",
    follows: "Follows",
    mutual: (n: string) => `${n} mutual`,
    ratersReturning: "Returning raters",
    ratersHint: "Accounts ≥7d that rated (7d)",
    appTitle: "App usage",
    appSub: "Time in app and most-navigated sections (screen_views since May 29, capped at 10 min/screen)",
    timePerUser: "Time / user",
    median: (n: number) => `Median: ${n} min`,
    totalTime: "Total time",
    perScreen: "Per screen",
    usersWithNav: "Users with navigation",
    mostNavigated: "Most-navigated sections",
    noData: "No data",
    minShort: "min",
    loadingTitles: "Loading titles…",
    noDataPeriod: "No data in the period",
    noDataTmdb: "No TMDB data",
    moviesMostViewed: "Most-watched movies on Peekr",
    seriesMostViewed: "Most-watched series on Peekr",
    mostViewedSub: "By number of views in the country and period",
    moviesTopPeekr: "Top-rated movies on Peekr",
    seriesTopPeekr: "Top-rated series on Peekr",
    topPeekrSub: "Average rating from country users (min. 3 ratings)",
    moviesTopTmdb: "Top-rated movies on TMDB",
    seriesTopTmdb: "Top-rated series on TMDB",
    topTmdbSub: "TMDB vote_average among the period's active titles",
    actorsTitle: "Trending actors (TMDB)",
    actorsSub: "People trending this week — global (TMDB can't filter by region)",
    badgeViews: (n: string) => `${n} views`,
    sec_feed: "Feed",
    sec_explore: "Explore",
    sec_explore_search: "Search (Explore)",
    sec_activity: "Activity",
    sec_activity_ranking: "Ranking",
    sec_inbox: "Inbox",
    sec_profile: "Own profile",
    sec_title: "Title page",
    sec_detail: "Title detail",
    sec_actor: "Actor",
    sec_user: "User profile",
    sec_peeklist: "Peeklist",
    sec_watchlist: "Watchlist",
  },
  pt: {
    metricsFor: "Métricas de",
    tabCountry: "Métricas do País",
    tabTitles: "Métricas de Títulos",
    presetToday: "Hoje",
    presetYesterday: "Ontem",
    preset7d: "7 dias",
    preset30d: "30 dias",
    preset90d: "90 dias",
    custom: "Personalizado",
    onlyOnboarded: "Só onboarded",
    onlyOnboardedTip: "Considerar só usuários que completaram o onboarding",
    loading: "Carregando…",
    denied: "Acesso não autorizado",
    loadingMetrics: "Carregando métricas…",
    globalTitle: "Total do país",
    globalSub: "Totais acumulados (todo o histórico)",
    totalUsers: "Usuários totais",
    onboardingDone: "Onboarding completo",
    totalRatings: "Avaliações totais",
    inWatchlist: "Na watchlist",
    audienceTitle: "Audiência do período",
    audienceSub: "Installs e onboarding no intervalo selecionado",
    newInstalls: "Novos installs",
    prevPeriod: (n: string) => `Período anterior: ${n}`,
    onboardingRate: "Taxa de onboarding",
    growthTitle: "Crescimento de audiência",
    growthSub: "Usuários acumulados do país no período",
    platformTitle: "Plataforma",
    platformSub: "Novos installs por plataforma",
    providerTitle: "Provider",
    providerSub: "Método de cadastro (Google / Apple / email)",
    retentionTitle: "Retenção",
    retentionSub: (days: string, plural: boolean) =>
      `Média diária do período (${days} dia${plural ? "s" : ""}). Uso real = navegou conteúdo ou fez uma ação. 'contrib' = só ações explícitas pós-install.`,
    dauAvg: "DAU méd/dia",
    wauAvg: "WAU méd/dia",
    mauAvg: "MAU méd/dia",
    northStarAvg: "North Star méd/dia",
    weuHint: "WEU (contas ≥7d)",
    dauMau: "DAU / MAU",
    stickyDaily: "Stickiness diário",
    wauMau: "WAU / MAU",
    stickyWeekly: "Stickiness semanal",
    churnRisk: "Risco de churn",
    resurrected: "Ressuscitados",
    firstTimeActive: "Ativos pela 1ª vez",
    thisWeek: "Esta semana",
    contrib: (n: number) => `contrib: ${n}`,
    wowTitle: "Retenção semana a semana (WoW)",
    wowSub: "% dos ativos de uma semana que voltam na seguinte",
    dailyDauTitle: "Atividade diária (DAU)",
    dailyDauSub: "Usuários ativos por dia no período",
    behaviorTitle: "Comportamento",
    behaviorSub: (n: string) => `Usuários ativos no período: ${n}`,
    ratings: "Avaliações",
    perActive: (n: number) => `${n} por ativo`,
    comments: "Comentários",
    watchlist: "Watchlist",
    peeklistsCreated: "Peeklists criadas",
    items: (n: string) => `${n} itens`,
    likesTitles: "Likes (títulos)",
    likesComments: "Likes (comentários)",
    follows: "Follows",
    mutual: (n: string) => `${n} mútuos`,
    ratersReturning: "Avaliadores retornando",
    ratersHint: "Contas ≥7d que avaliaram (7d)",
    appTitle: "Uso do app",
    appSub: "Tempo no app e seções mais navegadas (screen_views desde 29-mai, limitado a 10 min/tela)",
    timePerUser: "Tempo / usuário",
    median: (n: number) => `Mediana: ${n} min`,
    totalTime: "Tempo total",
    perScreen: "Por tela",
    usersWithNav: "Usuários com navegação",
    mostNavigated: "Seções mais navegadas",
    noData: "Sem dados",
    minShort: "min",
    loadingTitles: "Carregando títulos…",
    noDataPeriod: "Sem dados no período",
    noDataTmdb: "Sem dados do TMDB",
    moviesMostViewed: "Filmes mais vistos no Peekr",
    seriesMostViewed: "Séries mais vistas no Peekr",
    mostViewedSub: "Por quantidade de visualizações no país e período",
    moviesTopPeekr: "Filmes mais bem avaliados no Peekr",
    seriesTopPeekr: "Séries mais bem avaliadas no Peekr",
    topPeekrSub: "Média de avaliação dos usuários do país (mín. 3 avaliações)",
    moviesTopTmdb: "Filmes mais bem avaliados no TMDB",
    seriesTopTmdb: "Séries mais bem avaliadas no TMDB",
    topTmdbSub: "vote_average do TMDB entre os títulos ativos do período",
    actorsTitle: "Atores em alta (TMDB)",
    actorsSub: "Pessoas em alta esta semana — global (TMDB não permite filtrar por região)",
    badgeViews: (n: string) => `${n} visualizações`,
    sec_feed: "Feed",
    sec_explore: "Explorar",
    sec_explore_search: "Busca (Explore)",
    sec_activity: "Atividade",
    sec_activity_ranking: "Ranking",
    sec_inbox: "Inbox",
    sec_profile: "Perfil próprio",
    sec_title: "Página do título",
    sec_detail: "Detalhe do título",
    sec_actor: "Ator",
    sec_user: "Perfil de usuário",
    sec_peeklist: "Peeklist",
    sec_watchlist: "Watchlist",
  },
} as const;

export function dashTexts(lang: Lang) {
  return DICT[lang];
}

// Maps a logged screen path to its localized label.
export function sectionLabel(screen: string, t: DashTexts): string {
  const map: Record<string, string> = {
    "/feed": t.sec_feed,
    "/explore": t.sec_explore,
    "/explore/search": t.sec_explore_search,
    "/activity": t.sec_activity,
    "/activity/ranking": t.sec_activity_ranking,
    "/inbox": t.sec_inbox,
    "/profile": t.sec_profile,
    "/title/:type/:id": t.sec_title,
    "/detail": t.sec_detail,
    "/actor/:id": t.sec_actor,
    "/u/:username": t.sec_user,
    "/profile/peeklists/:id": t.sec_peeklist,
    "/watchlist": t.sec_watchlist,
  };
  return map[screen] ?? screen;
}
